//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lens.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lens.Translations.ParserMessages", typeof(ParserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound errors: {0}.
        /// </summary>
        public static string CompoundErrors {
            get {
                return ResourceManager.GetString("CompoundErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error case: {0}.
        /// </summary>
        public static string ErrorCase {
            get {
                return ResourceManager.GetString("ErrorCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message: {0}.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0}.
        /// </summary>
        public static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible happened.
        /// </summary>
        public static string ImpossibleHappened {
            get {
                return ResourceManager.GetString("ImpossibleHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect indentation.
        /// </summary>
        public static string IncorrectIndentation {
            get {
                return ResourceManager.GetString("IncorrectIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexem expected: {0}.
        /// </summary>
        public static string LexemExpected {
            get {
                return ResourceManager.GetString("LexemExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested errors: {0}.
        /// </summary>
        public static string NestedErrors {
            get {
                return ResourceManager.GetString("NestedErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      or .
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        public static string QuoteString {
            get {
                return ResourceManager.GetString("QuoteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String expected: &quot;{0}&quot;.
        /// </summary>
        public static string StringExpected {
            get {
                return ResourceManager.GetString("StringExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected string: &quot;{0}&quot;.
        /// </summary>
        public static string StringUnexpected {
            get {
                return ResourceManager.GetString("StringUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected: {0}.
        /// </summary>
        public static string Unexpected {
            get {
                return ResourceManager.GetString("Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown binary operator: {0}.
        /// </summary>
        public static string UnknownBinaryOperator {
            get {
                return ResourceManager.GetString("UnknownBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown boolean value: {0}.
        /// </summary>
        public static string UnknownBooleanValue {
            get {
                return ResourceManager.GetString("UnknownBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cast operator: {0}.
        /// </summary>
        public static string UnknownCastOperator {
            get {
                return ResourceManager.GetString("UnknownCastOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown comparison operator: {0}.
        /// </summary>
        public static string UnknownComparisonOperator {
            get {
                return ResourceManager.GetString("UnknownComparisonOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error: {0}.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown logical operator: {0}.
        /// </summary>
        public static string UnknownLogicalOperator {
            get {
                return ResourceManager.GetString("UnknownLogicalOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type operator: {0}.
        /// </summary>
        public static string UnknownTypeOperator {
            get {
                return ResourceManager.GetString("UnknownTypeOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown unary operator: {0}.
        /// </summary>
        public static string UnknownUnaryOperator {
            get {
                return ResourceManager.GetString("UnknownUnaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown value binding type: {0}.
        /// </summary>
        public static string UnknownValueBindingType {
            get {
                return ResourceManager.GetString("UnknownValueBindingType", resourceCulture);
            }
        }
    }
}
