//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lens.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lens.Translations.ParserMessages", typeof(ParserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument type is expected!.
        /// </summary>
        internal static string ArgTypeExpected {
            get {
                return ResourceManager.GetString("ArgTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&lt;|&apos; statements must be indented!.
        /// </summary>
        internal static string ArgumentPassIndentExpected {
            get {
                return ResourceManager.GetString("ArgumentPassIndentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method call arguments are expected!.
        /// </summary>
        internal static string ArgumentsExpected {
            get {
                return ResourceManager.GetString("ArgumentsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An array must contain at least one item!.
        /// </summary>
        internal static string ArrayItem {
            get {
                return ResourceManager.GetString("ArrayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment expression is expected!.
        /// </summary>
        internal static string AssignExpressionExpected {
            get {
                return ResourceManager.GetString("AssignExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch clause is expected!.
        /// </summary>
        internal static string CatchExpected {
            get {
                return ResourceManager.GetString("CatchExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code block is expected!.
        /// </summary>
        internal static string CodeBlockExpected {
            get {
                return ResourceManager.GetString("CodeBlockExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition block is expected!.
        /// </summary>
        internal static string ConditionBlockExpected {
            get {
                return ResourceManager.GetString("ConditionBlockExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition is expected!.
        /// </summary>
        internal static string ConditionExpected {
            get {
                return ResourceManager.GetString("ConditionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition expression is expected!.
        /// </summary>
        internal static string ConditionExpressionExpected {
            get {
                return ResourceManager.GetString("ConditionExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dictionary must contain at least one item!.
        /// </summary>
        internal static string DictionaryItem {
            get {
                return ResourceManager.GetString("DictionaryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary key expression is expected!.
        /// </summary>
        internal static string DictionaryKeyExpected {
            get {
                return ResourceManager.GetString("DictionaryKeyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary value expression is expected!.
        /// </summary>
        internal static string DictionaryValueExpected {
            get {
                return ResourceManager.GetString("DictionaryValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handler code block is expected!.
        /// </summary>
        internal static string ExceptionHandlerExpected {
            get {
                return ResourceManager.GetString("ExceptionHandlerExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type signature is expected!.
        /// </summary>
        internal static string ExceptionTypeExpected {
            get {
                return ResourceManager.GetString("ExceptionTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is expected!.
        /// </summary>
        internal static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function body is expected!.
        /// </summary>
        internal static string FunctionBodyExpected {
            get {
                return ResourceManager.GetString("FunctionBodyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function definition is expected!.
        /// </summary>
        internal static string FunctionDefExpected {
            get {
                return ResourceManager.GetString("FunctionDefExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function name must be an identifier!.
        /// </summary>
        internal static string FunctionIdentifierExpected {
            get {
                return ResourceManager.GetString("FunctionIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function return type is expected!.
        /// </summary>
        internal static string FunctionReturnExpected {
            get {
                return ResourceManager.GetString("FunctionReturnExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier is expected!.
        /// </summary>
        internal static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index expression is expected!.
        /// </summary>
        internal static string IndexExpressionExpected {
            get {
                return ResourceManager.GetString("IndexExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer expression is expected!.
        /// </summary>
        internal static string InitExpressionExpected {
            get {
                return ResourceManager.GetString("InitExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer expression or type signature is expected!.
        /// </summary>
        internal static string InitExpressionOrTypeExpected {
            get {
                return ResourceManager.GetString("InitExpressionOrTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer expressions must be separated by a newline!.
        /// </summary>
        internal static string InitExpressionSeparatorExpected {
            get {
                return ResourceManager.GetString("InitExpressionSeparatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid double!.
        /// </summary>
        internal static string InvalidDouble {
            get {
                return ResourceManager.GetString("InvalidDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid integer!.
        /// </summary>
        internal static string InvalidInteger {
            get {
                return ResourceManager.GetString("InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke passes must be separated by a newline!.
        /// </summary>
        internal static string InvokePassSeparatorExpected {
            get {
                return ResourceManager.GetString("InvokePassSeparatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list must contain at least one item!.
        /// </summary>
        internal static string ListItem {
            get {
                return ResourceManager.GetString("ListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop body block is expected!.
        /// </summary>
        internal static string LoopBodyExpected {
            get {
                return ResourceManager.GetString("LoopBodyExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop body expression is expected!.
        /// </summary>
        internal static string LoopExpressionExpected {
            get {
                return ResourceManager.GetString("LoopExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignable expression is expected!.
        /// </summary>
        internal static string LvalueExpected {
            get {
                return ResourceManager.GetString("LvalueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member name is expected!.
        /// </summary>
        internal static string MemberNameExpected {
            get {
                return ResourceManager.GetString("MemberNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;|&gt;&apos; statements must be indented!.
        /// </summary>
        internal static string MethodPassIndentExpected {
            get {
                return ResourceManager.GetString("MethodPassIndentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A namespace is expected!.
        /// </summary>
        internal static string NamespaceExpected {
            get {
                return ResourceManager.GetString("NamespaceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements must be separated by newlines!.
        /// </summary>
        internal static string NewlineSeparatorExpected {
            get {
                return ResourceManager.GetString("NewlineSeparatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range end expression is expected!.
        /// </summary>
        internal static string RangeEndExpected {
            get {
                return ResourceManager.GetString("RangeEndExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record field name must be an identifier!.
        /// </summary>
        internal static string RecordFieldIdentifierExpected {
            get {
                return ResourceManager.GetString("RecordFieldIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record field type signature is expected!.
        /// </summary>
        internal static string RecordFieldTypeExpected {
            get {
                return ResourceManager.GetString("RecordFieldTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record name must be an identifier!.
        /// </summary>
        internal static string RecordIdentifierExpected {
            get {
                return ResourceManager.GetString("RecordIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record body must be indented block!.
        /// </summary>
        internal static string RecordIndentExpected {
            get {
                return ResourceManager.GetString("RecordIndentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record fields must be separated by a newline!.
        /// </summary>
        internal static string RecordSeparatorExpected {
            get {
                return ResourceManager.GetString("RecordSeparatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence expression is expected!.
        /// </summary>
        internal static string SequenceExpected {
            get {
                return ResourceManager.GetString("SequenceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; expected!.
        /// </summary>
        internal static string SymbolExpected {
            get {
                return ResourceManager.GetString("SymbolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try block is expected!.
        /// </summary>
        internal static string TryBlockExpected {
            get {
                return ResourceManager.GetString("TryBlockExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tuple must contain at least one item!.
        /// </summary>
        internal static string TupleItem {
            get {
                return ResourceManager.GetString("TupleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type argument is expected!.
        /// </summary>
        internal static string TypeArgumentExpected {
            get {
                return ResourceManager.GetString("TypeArgumentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name must be an identifier!.
        /// </summary>
        internal static string TypeIdentifierExpected {
            get {
                return ResourceManager.GetString("TypeIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type body must be indented block!.
        /// </summary>
        internal static string TypeIndentExpected {
            get {
                return ResourceManager.GetString("TypeIndentExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type label name must be an identifier!.
        /// </summary>
        internal static string TypeLabelIdentifierExpected {
            get {
                return ResourceManager.GetString("TypeLabelIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag type signature is expected!.
        /// </summary>
        internal static string TypeLabelTagTypeExpected {
            get {
                return ResourceManager.GetString("TypeLabelTagTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type labels must be separated by a newline!.
        /// </summary>
        internal static string TypeSeparatorExpected {
            get {
                return ResourceManager.GetString("TypeSeparatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type signature is expected!.
        /// </summary>
        internal static string TypeSignatureExpected {
            get {
                return ResourceManager.GetString("TypeSignatureExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown kind of statement!.
        /// </summary>
        internal static string UnknownStatement {
            get {
                return ResourceManager.GetString("UnknownStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name must be an identifier!.
        /// </summary>
        internal static string VarIdentifierExpected {
            get {
                return ResourceManager.GetString("VarIdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable type is expected!.
        /// </summary>
        internal static string VarTypeExpected {
            get {
                return ResourceManager.GetString("VarTypeExpected", resourceCulture);
            }
        }
    }
}
