//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lens.SyntaxTree.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParserLexems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserLexems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lens.SyntaxTree.Translations.ParserLexems", typeof(ParserLexems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оператор доступа.
        /// </summary>
        public static string AccessorExpr {
            get {
                return ResourceManager.GetString("AccessorExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оператор присваивания.
        /// </summary>
        public static string AssignExpr {
            get {
                return ResourceManager.GetString("AssignExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to атомарное выражение.
        /// </summary>
        public static string AtomarExpr {
            get {
                return ResourceManager.GetString("AtomarExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to блок.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение блока.
        /// </summary>
        public static string BlockExpr {
            get {
                return ResourceManager.GetString("BlockExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to строка блока.
        /// </summary>
        public static string BlockLine {
            get {
                return ResourceManager.GetString("BlockLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аргумент по ссылке.
        /// </summary>
        public static string ByRefArg {
            get {
                return ResourceManager.GetString("ByRefArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение catch.
        /// </summary>
        public static string CatchExpr {
            get {
                return ResourceManager.GetString("CatchExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to элемент словаря.
        /// </summary>
        public static string DictEntryExpr {
            get {
                return ResourceManager.GetString("DictEntryExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дробное число.
        /// </summary>
        public static string Double {
            get {
                return ResourceManager.GetString("Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перечисление.
        /// </summary>
        public static string EnumerationExpr {
            get {
                return ResourceManager.GetString("EnumerationExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string Expr {
            get {
                return ResourceManager.GetString("Expr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to определение функции.
        /// </summary>
        public static string FuncDef {
            get {
                return ResourceManager.GetString("FuncDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to параметры функции.
        /// </summary>
        public static string FuncParams {
            get {
                return ResourceManager.GetString("FuncParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to идентификатор.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение if.
        /// </summary>
        public static string IfExpr {
            get {
                return ResourceManager.GetString("IfExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to целое число.
        /// </summary>
        public static string Int {
            get {
                return ResourceManager.GetString("Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вызов метода.
        /// </summary>
        public static string InvokeExpr {
            get {
                return ResourceManager.GetString("InvokeExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to список вызова.
        /// </summary>
        public static string InvokeList {
            get {
                return ResourceManager.GetString("InvokeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to анонимная функция.
        /// </summary>
        public static string LambdaExpr {
            get {
                return ResourceManager.GetString("LambdaExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr {
            get {
                return ResourceManager.GetString("LineExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr0 {
            get {
                return ResourceManager.GetString("LineExpr0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr1 {
            get {
                return ResourceManager.GetString("LineExpr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr2 {
            get {
                return ResourceManager.GetString("LineExpr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr3 {
            get {
                return ResourceManager.GetString("LineExpr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr4 {
            get {
                return ResourceManager.GetString("LineExpr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr5 {
            get {
                return ResourceManager.GetString("LineExpr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr6 {
            get {
                return ResourceManager.GetString("LineExpr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string LineExpr7 {
            get {
                return ResourceManager.GetString("LineExpr7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to литерал.
        /// </summary>
        public static string Literal {
            get {
                return ResourceManager.GetString("Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инструкция.
        /// </summary>
        public static string LocalStmt {
            get {
                return ResourceManager.GetString("LocalStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lvalue.
        /// </summary>
        public static string LValue {
            get {
                return ResourceManager.GetString("LValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пространство имён.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инициализатор массива.
        /// </summary>
        public static string NewArrayExpr {
            get {
                return ResourceManager.GetString("NewArrayExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инициализатор словаря.
        /// </summary>
        public static string NewDictExpr {
            get {
                return ResourceManager.GetString("NewDictExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оператор new.
        /// </summary>
        public static string NewExpr {
            get {
                return ResourceManager.GetString("NewExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инициализатор списка.
        /// </summary>
        public static string NewListExpr {
            get {
                return ResourceManager.GetString("NewListExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инициализатор объекта.
        /// </summary>
        public static string NewObjExpr {
            get {
                return ResourceManager.GetString("NewObjExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to инициализатор кортежа.
        /// </summary>
        public static string NewTupleExpr {
            get {
                return ResourceManager.GetString("NewTupleExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявление записи.
        /// </summary>
        public static string RecordDef {
            get {
                return ResourceManager.GetString("RecordDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявление поля записи.
        /// </summary>
        public static string RecordDefStmt {
            get {
                return ResourceManager.GetString("RecordDefStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rvalue.
        /// </summary>
        public static string RValue {
            get {
                return ResourceManager.GetString("RValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знак.
        /// </summary>
        public static string Sign1 {
            get {
                return ResourceManager.GetString("Sign1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знак.
        /// </summary>
        public static string Sign2 {
            get {
                return ResourceManager.GetString("Sign2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знак.
        /// </summary>
        public static string Sign3 {
            get {
                return ResourceManager.GetString("Sign3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to знак.
        /// </summary>
        public static string Sign4 {
            get {
                return ResourceManager.GetString("Sign4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение.
        /// </summary>
        public static string Stmt {
            get {
                return ResourceManager.GetString("Stmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to строка.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение throw.
        /// </summary>
        public static string ThrowExpr {
            get {
                return ResourceManager.GetString("ThrowExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение try.
        /// </summary>
        public static string TryExpr {
            get {
                return ResourceManager.GetString("TryExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявление типа.
        /// </summary>
        public static string TypeDef {
            get {
                return ResourceManager.GetString("TypeDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявление метки.
        /// </summary>
        public static string TypeDefStmt {
            get {
                return ResourceManager.GetString("TypeDefStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оператор приведения типов.
        /// </summary>
        public static string TypeOperatorExpr {
            get {
                return ResourceManager.GetString("TypeOperatorExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to параметры типа.
        /// </summary>
        public static string TypeParams {
            get {
                return ResourceManager.GetString("TypeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение using.
        /// </summary>
        public static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявление переменной.
        /// </summary>
        public static string VarDeclExpr {
            get {
                return ResourceManager.GetString("VarDeclExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выражение while.
        /// </summary>
        public static string WhileExpr {
            get {
                return ResourceManager.GetString("WhileExpr", resourceCulture);
            }
        }
    }
}
