namespace Lens.Compiler.Entities
{
    internal static class EntityNames
    {
        /// <summary>
        /// The template for an assembly generated by LENS.
        /// </summary>
        public const string AssemblyNameTemplate = "_CompiledAssembly{0}";

        /// <summary>
        /// The name of the main type in the assembly.
        /// </summary>
        public const string MainTypeName = "<Script>";

        /// <summary>
        /// The name of the main method in which the code is situated.
        /// </summary>
        public const string RunMethodName = "Run";

        /// <summary>
        /// The name the main method takes instead when the script awaits at its top level, and so
        /// hands out a task rather than a value.
        /// </summary>
        public const string RunAsyncMethodName = "RunAsync";

        /// <summary>
        /// The name of the assembly entry point (when it's saved as exe).
        /// </summary>
        public const string EntryPointMethodName = "Main";

        /// <summary>
        /// The name of a field that contains a pointer to root type.
        /// </summary>
        public const string ParentScopeFieldName = "<root>";

        /// <summary>
        /// The template for implicitly defined local variables.
        /// </summary>
        public const string ImplicitVariableNameTemplate = "<loc_{0}>";

        /// <summary>
        /// The template for closure type field names.
        /// </summary>
        public const string ClosureFieldNameTemplate = "<cf_{0}_{1}>";

        /// <summary>
        /// The template for closure type names.
        /// </summary>
        public const string ClosureTypeNameTemplate = "<ct_{0}>";

        /// <summary>
        /// The template for closure method names.
        /// </summary>
        public const string ClosureMethodNameTemplate = "<cm_{0}_{1}>";

        /// <summary>
        /// The template for pure methods.
        /// Actual method name is used for the newly generated wrapper, and the original method is renamed using this template.
        /// </summary>
        public const string PureMethodNameTemplate = "<pure_{0}>";

        /// <summary>
        /// The template for a field name which is used to store cached results of pure functions.
        /// </summary>
        public const string PureMethodCacheNameTemplate = "<pc_{0}>";

        /// <summary>
        /// The template for a holder class that keeps the cache of a generic pure function.
        /// </summary>
        public const string PureMethodCacheTypeNameTemplate = "<pct_{0}>";

        /// <summary>
        /// The template for a field name which is used to store the flag indicating the pure function's result has been calculated.
        /// </summary>
        public const string PureMethodCacheFlagNameTemplate = "<pcf_{0}>";

        /// <summary>
        /// The template for an autogenerated lamda's argument name.
        /// </summary>
        internal const string AnonymousArgumentTemplate = "<arg_{0}>";

        /// <summary>
        /// The template for the class a state machine is compiled into.
        /// </summary>
        public const string StateMachineTypeNameTemplate = "<sm_{0}>";

        /// <summary>
        /// The name of the field that says where in its body a suspended state machine is.
        /// </summary>
        public const string StateFieldName = "<state>";

        /// <summary>
        /// The name of the field that holds the value an iterator has most recently yielded.
        /// </summary>
        public const string CurrentFieldName = "<current>";

        /// <summary>
        /// The name of the field that says a suspended iterator is being abandoned rather than
        /// resumed, so that MoveNext runs the finally blocks it still owes and stops.
        /// </summary>
        public const string DisposingFieldName = "<disposing>";

        /// <summary>
        /// The name of the method that implements IEnumerable.GetEnumerator, which cannot be
        /// called GetEnumerator because the generic interface has claimed that name.
        /// </summary>
        public const string NonGenericGetEnumeratorName = "<GetEnumerator>";

        /// <summary>
        /// The name of the method that implements IEnumerator.Current, for the same reason.
        /// </summary>
        public const string NonGenericCurrentGetterName = "<get_Current>";

        /// <summary>
        /// The name of the field that holds the task an async function handed to its caller.
        /// </summary>
        public const string CompletionFieldName = "<completion>";

        /// <summary>
        /// The name of the method that calls MoveNext with a handler around it. MoveNext cannot
        /// catch its own exceptions, because nothing may be resumed into a protected region.
        /// </summary>
        public const string ResumeMethodName = "<Resume>";
    }
}