namespace Lens.Compiler.Entities
{
	internal enum TypeContentsKind
	{
		/// <summary>
		/// Represents an entity declared by the user: function, type or record
		/// </summary>
		UserDefined,

		/// <summary>
		/// Entity automatically generated by the compiler: pure function, equality comparers, hashcode generators etc.
		/// </summary>
		AutoGenerated,

		/// <summary>
		/// Entity related to closure mechanism: backing field or closure method
		/// </summary>
		Closure
	}
}
