<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net47;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net47'">
    <DefineConstants>NET_CLASSIC</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' != 'net47'">
    <DefineConstants>NET_CORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net47'">
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lens\Lens.csproj" />
  </ItemGroup>
</Project>
