using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using Lens.Compiler.Entities;
using Lens.Resolver;
using Lens.SyntaxTree;
using Lens.SyntaxTree.ControlFlow;
using Lens.SyntaxTree.Declarations;
using Lens.SyntaxTree.Declarations.Functions;
using Lens.SyntaxTree.Declarations.Types;
using Lens.Translations;
using Lens.Utils;

namespace Lens.Compiler
{
    internal partial class Context
    {
        #region Compilation essentials

        /// <summary>
        /// The main compilation method.
        /// Processes the list of nodes, performs all compilation stages.
        /// </summary>
        /// <returns>
        /// The instance of generated assembly's entry point class.
        /// </returns>
        public IScript Compile(IEnumerable<NodeBase> nodes)
        {
            IsEmitting = true;

            LoadTree(nodes);
            ThrowIfFailed();

            CreateInitialEntities(emit: true);
            ThrowIfFailed();

            TransformTree();
            ThrowIfFailed();

            EmitCode();
            FinalizeAssembly();

            var inst = Activator.CreateInstance(ResolveType(EntityNames.MainTypeName).Materialize());
            return inst as IScript;
        }

        /// <summary>
        /// Runs everything that is analysis and nothing that is emission: declarations are read,
        /// bodies are bound, captures are worked out, and diagnostics are collected. No IL is
        /// generated.
        ///
        /// This is the entry point a language server consumes. It does not throw on a bad script -
        /// the caller reads Diagnostics.
        /// </summary>
        public void Analyze(IEnumerable<NodeBase> nodes)
        {
            LoadTree(nodes);
            if (Diagnostics.HasErrors)
                return;

            CreateInitialEntities(emit: false);
            if (Diagnostics.HasErrors)
                return;

            BindTree();
        }

        /// <summary>
        /// Initializes the context from a stream of nodes.
        /// </summary>
        private void LoadTree(IEnumerable<NodeBase> nodes)
        {
            foreach (var currNode in nodes)
            {
                var node = currNode;
                WithRecovery(() =>
                    {
                        if (node is TypeDefinitionNode)
                            DeclareType(node as TypeDefinitionNode);
                        else if (node is RecordDefinitionNode)
                            DeclareRecord(node as RecordDefinitionNode);
                        else if (node is FunctionNode)
                            DeclareFunction(node as FunctionNode);
                        else if (node is UseNode)
                            DeclareOpenNamespace(node as UseNode);
                        else
                            DeclareScriptNode(node);
                    }
                );
            }
        }

        /// <summary>
        /// Creates all autogenerated code for user-defined types.
        /// </summary>
        /// <param name="emit">
        /// Whether the assembly-level entities are to be created along with the declarations they
        /// implement. An analysis-only run passes false and gets resolved signatures and no builders.
        /// </param>
        private void CreateInitialEntities(bool emit)
        {
#if NET_CLASSIC
            if (emit && Options.AllowSave && Options.SaveAsExe)
                CreateEntryPoint();
#endif

            ProcessEntities(false, emit);

            if (UnpreparedTypes.Count > 0)
            {
                foreach (var curr in UnpreparedTypes)
                    curr.CreateEntities();

                ProcessEntities(true, emit);
            }
        }

        /// <summary>
        /// Traverses all nodes, resolving and transforming them.
        /// </summary>
        private void TransformTree()
        {
            while (UnprocessedMethods.Count > 0)
            {
                var analysed = BindRound();

                // the entities declared by this round cannot be prepared once anything has
                // failed, so gather the round's diagnostics and stop here
                if (Diagnostics.HasErrors)
                    break;

                // a separate pass, and deliberately so: everything above decided what has to be
                // captured, everything below creates the assembly artefacts that implement it
                foreach (var curr in analysed)
                    WithRecovery(curr.EmitClosureEntities);

                if (Diagnostics.HasErrors)
                    break;

                PrepareEntities();
            }
        }

        /// <summary>
        /// Binds every method body without creating anything the assembly would hold.
        /// </summary>
        private void BindTree()
        {
            while (UnprocessedMethods.Count > 0)
            {
                BindRound();

                if (Diagnostics.HasErrors)
                    return;

                // a round may have declared entities of its own - a pure function's wrapper, say -
                // and the next round binds their bodies, so their signatures must be resolved first
                ResolveEntities();
            }
        }

        /// <summary>
        /// Transforms and binds one round of pending method bodies, and works out what each of them
        /// captures. Returns the methods that came through without a diagnostic, which are the ones
        /// whose closure entities may be created.
        /// </summary>
        private List<MethodEntityBase> BindRound()
        {
            var methods = UnprocessedMethods.OrderByDescending(x => x.IsImported).ToArray();
            UnprocessedMethods.Clear();

            // closure method bodies have been processed as contents of their lambda
            // no need to process them twice
            var pending = methods.Where(x => x.Kind != TypeContentsKind.Closure);
            var analysed = new List<MethodEntityBase>();

            foreach (var curr in pending)
            {
                var diagnosticsBefore = Diagnostics.Count;
                WithRecovery(curr.TransformBody);

                // closure analysis assumes the transform above has completed: walking a
                // half-transformed body only produces follow-up noise
                if (Diagnostics.Count != diagnosticsBefore)
                    continue;

                WithRecovery(curr.AnalyzeClosures);

                if (Diagnostics.Count == diagnosticsBefore)
                    analysed.Add(curr);
            }

            return analysed;
        }

        /// <summary>
        /// Generates the source code for all the declared methods.
        /// </summary>
        private void EmitCode()
        {
            foreach (var curr in _definedTypes)
                curr.Value.Compile();
        }

        /// <summary>
        /// Finalizes the assembly.
        /// </summary>
        private void FinalizeAssembly()
        {
            foreach (var curr in _definedTypes)
                if (!curr.Value.IsImported)
                    curr.Value.TypeBuilder.CreateTypeInfo();

#if NET_CLASSIC
            if (Options.AllowSave)
            {
                if (Options.SaveAsExe)
                {
                    var ep = ResolveMethod(ResolveType(EntityNames.MainTypeName), EntityNames.EntryPointMethodName);
                    MainAssembly.SetEntryPoint(ep.MethodInfo, PEFileKinds.ConsoleApplication);
                }

                MainAssembly.Save(Options.FileName);
            }
#endif
        }

        #endregion

        #region Error recovery

        /// <summary>
        /// Runs one unit of analysis, recording the problems it reports instead of letting them
        /// abort the whole compilation. This is what makes the compiler report more than one error.
        /// </summary>
        internal void WithRecovery(Action act)
        {
            var scopeDepth = _scopeStack.Count;

            try
            {
                act();
            }
            catch (LensCompilerException ex)
            {
                Diagnostics.Add(ex);
            }
            finally
            {
                // an aborted unit may have left scopes open: unwind them, or everything that
                // follows would resolve its names in the wrong frame
                while (_scopeStack.Count > scopeDepth)
                    _scopeStack.Pop();
            }
        }

        /// <summary>
        /// Surfaces the first recorded error as an exception, which is the shape the public API
        /// has always had.
        /// </summary>
        private void ThrowIfFailed()
        {
            var error = Diagnostics.FirstError();
            if (error != null)
                throw error.AsException();
        }

        #endregion

        #region Scope manipulation

        /// <summary>
        /// Add a new scope to the lookup list.
        /// </summary>
        public void EnterScope(Scope scope)
        {
            if (Scope == null)
            {
                if (scope.OuterScope == null && scope.Kind != ScopeKind.FunctionRoot)
                    throw new InvalidOperationException($"Scope of kind '{scope.Kind}' must have a parent!");
            }
            else
            {
                scope.OuterScope = Scope;
            }

            _scopeStack.Push(scope);
        }

        /// <summary>
        /// Remove the topmost scope from the lookup list.
        /// </summary>
        public Scope ExitScope()
        {
            if (Scope == null)
                throw new InvalidOperationException("No scope to exit!");

            return _scopeStack.Pop();
        }

        #endregion

        #region Compilation helpers

        /// <summary>
        /// Declares a new type.
        /// </summary>
        private void DeclareType(TypeDefinitionNode node)
        {
            if (node.Name == "_")
                Error(CompilerMessages.UnderscoreName);

            var mainType = CreateType(node.Name, prepare: false, genericParameters: CreateGenericParameters(node.TypeParameters, node.Name));
            mainType.Kind = TypeEntityKind.Type;

            // every label must be generic in the full parameter list of the parent, even a label
            // that does not mention it: the CLR has no other way for it to extend a constructed
            // generic base type
            var parentSignature = SelfSignature(node.Name, node.TypeParameters);

            foreach (var curr in node.Entries)
            {
                var tagName = curr.Name;
                var labelType = CreateType(
                    tagName,
                    parentSignature,
                    isSealed: true,
                    defaultCtor: false,
                    prepare: false,
                    genericParameters: CreateGenericParameters(node.TypeParameters, tagName)
                );
                labelType.Kind = TypeEntityKind.TypeLabel;

                var ctor = labelType.CreateConstructor(prepare: false);
                ctor.Kind = TypeContentsKind.AutoGenerated;
                if (curr.IsTagged)
                {
                    var tagField = labelType.CreateField("Tag", curr.TagType, prepare: false);
                    tagField.Kind = TypeContentsKind.UserDefined;

                    // the factory is just another generic function, so 'Baz value' infers Foo<T>
                    // through the same machinery that infers generics of imported methods
                    var labelSignature = SelfSignature(tagName, node.TypeParameters);
                    var staticCtor = MainType.CreateMethod(tagName, labelSignature, (IEnumerable<FunctionArgument>) null, isStatic: true, prepare: false);
                    staticCtor.Kind = TypeContentsKind.AutoGenerated;
                    staticCtor.GenericParameters = CreateGenericParameters(node.TypeParameters, tagName);

                    // the arguments cannot be shared: each of them memoizes its resolved type,
                    // and the tag type means the label's own parameters in one case and the
                    // factory method's parameters in the other
                    ctor.Arguments = MakeTagArguments(curr.TagType);
                    staticCtor.Arguments = MakeTagArguments(curr.TagType);

                    ctor.Body.Add(
                        Expr.SetMember(Expr.This(), "Tag", Expr.Get("value"))
                    );

                    staticCtor.Body.Add(
                        Expr.New(labelSignature, Expr.Get("value"))
                    );
                }
            }
        }

        /// <summary>
        /// Builds the signature by which a declaration refers to itself: the plain name for a
        /// simple type, or the name applied to its own parameters for a generic one.
        /// </summary>
        private static TypeSignature SelfSignature(string name, List<TypeParameterDefinition> typeParameters)
        {
            if (typeParameters == null || typeParameters.Count == 0)
                return name;

            return new TypeSignature(name, typeParameters.Select(x => new TypeSignature(x.Name)).ToArray());
        }

        /// <summary>
        /// Creates the argument list of a tagged label's constructor or factory method.
        /// </summary>
        private static HashList<FunctionArgument> MakeTagArguments(TypeSignature tagType)
        {
            return new HashList<FunctionArgument> {{"value", new FunctionArgument("value", tagType)}};
        }

        /// <summary>
        /// Declares a new record.
        /// </summary>
        private void DeclareRecord(RecordDefinitionNode node)
        {
            if (node.Name == "_")
                Error(CompilerMessages.UnderscoreName);

            var recType = CreateType(node.Name, isSealed: true, prepare: false, genericParameters: CreateGenericParameters(node.TypeParameters, node.Name));
            recType.Kind = TypeEntityKind.Record;

            var recCtor = recType.CreateConstructor(prepare: false);
            recCtor.Kind = TypeContentsKind.AutoGenerated;

            foreach (var curr in node.Entries)
            {
                var field = recType.CreateField(curr.Name, curr.Type, prepare: false);
                field.Kind = TypeContentsKind.UserDefined;
                var argName = "_" + field.Name.ToLowerInvariant();

                recCtor.Arguments.Add(argName, new FunctionArgument(argName, curr.Type));
                recCtor.Body.Add(
                    Expr.SetMember(Expr.This(), field.Name, Expr.Get(argName))
                );
            }
        }

        /// <summary>
        /// Declares a new function.
        /// </summary>
        private void DeclareFunction(FunctionNode node)
        {
            if (node.Name == "_")
                Error(CompilerMessages.UnderscoreName);

            var isVariadic = false;

            // validation
            if (node.Arguments.Count > 0)
            {
                for (var idx = 0; idx < node.Arguments.Count; idx++)
                {
                    var curr = node.Arguments[idx];
                    if (curr.Name == "_")
                        curr.Name = Unique.AnonymousArgName();

                    if (curr.Type == TypeEntryCache.Of<UnspecifiedType>())
                        Error(CompilerMessages.LambdaArgTypeUnknown);

                    if (curr.IsVariadic)
                    {
                        if (idx < node.Arguments.Count - 1)
                            Error(CompilerMessages.VariadicArgumentNotLast);

                        isVariadic = true;
                    }
                }
            }
            else
            {
                if (node.Name == EntityNames.RunMethodName || node.Name == EntityNames.EntryPointMethodName)
                    Error(CompilerMessages.ReservedFunctionRedefinition, node.Name);
            }

            var method = MainType.CreateMethod(node.Name, node.ReturnTypeSignature, node.Arguments, true, prepare: false);
            method.Kind = TypeContentsKind.UserDefined;
            method.IsPure = node.IsPure;
            method.IsVariadic = isVariadic;
            method.GenericParameters = CreateGenericParameters(node.TypeParameters, node.Name);
            method.Body = node.Body;
        }

        /// <summary>
        /// Opens a new namespace for current script.
        /// </summary>
        private void DeclareOpenNamespace(UseNode node)
        {
            if (!Namespaces.ContainsKey(node.Namespace))
                Namespaces.Add(node.Namespace, true);
        }

        /// <summary>
        /// Adds a new node to the main script's body.
        /// </summary>
        private void DeclareScriptNode(NodeBase node)
        {
            MainMethod.Body.Add(node);
        }

        /// <summary>
        /// Creates all assembly-level entities for types, fields, methods and constructors.
        /// </summary>
        private void PrepareEntities(bool clearTypes = true)
        {
            ProcessEntities(clearTypes, true);
        }

        /// <summary>
        /// Resolves the signatures of all pending types, fields, methods and constructors without
        /// creating any of the assembly-level entities that implement them.
        /// </summary>
        private void ResolveEntities(bool clearTypes = true)
        {
            ProcessEntities(clearTypes, false);
        }

        /// <summary>
        /// Runs preparation over everything that is pending: the analysis half always, and the
        /// emission half right after it when there is an assembly to emit into.
        ///
        /// The two halves of one entity stay adjacent. Nothing forces that any more - a signature
        /// resolves into an entry and needs no builders - but separating them would reorder the
        /// DefineType and DefineMethod calls, and the order in which an assembly is built is part of
        /// what this compiler produces.
        /// </summary>
        private void ProcessEntities(bool clearTypes, bool emit)
        {
            if (UnpreparedTypes.Count > 0)
            {
                foreach (var curr in UnpreparedTypes)
                {
                    curr.ResolveSelf();

                    if (emit)
                        curr.EmitSelf();
                }

                if (clearTypes)
                    UnpreparedTypes.Clear();
            }

            if (UnpreparedTypeContents.Count > 0)
            {
                foreach (var curr in UnpreparedTypeContents)
                {
                    // a member of a generic type refers to the type's parameters in its signature
                    WithGenericScope(curr.ContainerType.GenericParameters, () =>
                        {
                            curr.ResolveSelf();

                            if (emit)
                                curr.EmitSelf();

                            var me = curr as MethodEntity;
                            if (me != null)
                                me.ContainerType.CheckMethod(me);
                        }
                    );
                }

                UnpreparedTypeContents.Clear();
            }
        }

        /// <summary>
        /// Creates the entry point for an assembly if it is supposed to be saved.
        /// The entry point method basically calls the Run method and discards the result.
        /// </summary>
        private void CreateEntryPoint()
        {
            var ep = MainType.CreateMethod(EntityNames.EntryPointMethodName, "Void", args: null, isStatic: true);
            ep.Kind = TypeContentsKind.AutoGenerated;
            ep.Body = Expr.Block(
                Expr.Invoke(Expr.New(EntityNames.MainTypeName), "Run"),
                Expr.Unit()
            );
        }

        #endregion
    }
}