using System;
using System.Collections.Generic;
using Lens.Compiler.Entities;
using Lens.Translations;

namespace Lens.Compiler
{
	/// <summary>
	/// A list of variables defined in a particular code block.
	/// </summary>
	internal class ScopeFrame
	{
		public ScopeFrame()
		{
			Names = new Dictionary<string, LocalName>();
		}

		/// <summary>
		/// The lookup table of names defined in current scope.
		/// </summary>
		public readonly Dictionary<string, LocalName> Names;

		/// <summary>
		/// The pointer to containing frame.
		/// </summary>
		public ScopeFrame OuterScope;

		/// <summary>
		/// Checks if this scope must create a closure class of its own instead of using parent class.
		/// Is true for root scopes and loops.
		/// </summary>
		public readonly bool IsClosureSignificant;

		#region Methods

		/// <summary>
		/// Gets information about a local name.
		/// </summary>
		public LocalName FindName(string name)
		{
			LocalName local = null;
			find(name, (loc, idx) => local = loc.GetClosuredCopy(idx));
			return local;
		}

		/// <summary>
		/// Declares a new name in the current scope.
		/// </summary>
		public LocalName DeclareName(string name, Type type, bool isConst, bool isRefArg = false)
		{
			if (find(name))
				throw new LensCompilerException(string.Format(CompilerMessages.VariableDefined, name));

			var n = new LocalName(name, type, isConst, isRefArg);
			Names[name] = n;
			return n;
		}

		/// <summary>
		/// Declares a new variable with autogenerated name.
		/// This name cannot be closured.
		/// </summary>
		public LocalName DeclareImplicitName(Context ctx, Type type, bool isConst)
		{
			var lb = ctx.CurrentMethod.Generator.DeclareLocal(type);
			var name = string.Format(EntityNames.ImplicitVariableNameTemplate, lb.LocalIndex);
			var ln = new LocalName(name, type, isConst) { LocalBuilder = lb };
			Names[name] = ln;
			return ln;
		}

		/// <summary>
		/// Declares a new temp variable that is instantly initialized.
		/// </summary>
		public LocalName DeclareInternalName(string name, Context ctx, Type type, bool isConst)
		{
			var lb = ctx.CurrentMethod.Generator.DeclareLocal(type);
			var ln = new LocalName(name, type, isConst) { LocalBuilder = lb };
			Names[name] = ln;
			return ln;
		}

		/// <summary>
		/// Checks if the variable is being referenced in another scope.
		/// </summary>
		public void ReferenceName(string name)
		{
			var found = find(
				name,
				(loc, idx) =>
				{
					var closured = idx > 0;
					if (closured)
					{
						if (loc.LocalBuilder != null)
							throw new InvalidOperationException(CompilerMessages.ClosureImplicit);

						if (loc.IsRefArgument)
							throw new LensCompilerException(CompilerMessages.ClosureRef);
					}

					loc.IsClosured |= closured;
				}
			);

			if (!found)
				throw new LensCompilerException(string.Format(CompilerMessages.VariableNotFound, name));
		}

		/// <summary>
		/// Creates a closured method in the current scope's closure type using function argument records.
		/// </summary>
		public MethodEntity CreateClosureMethod(Context ctx, IEnumerable<FunctionArgument> args, TypeSignature returnType = null)
		{
		}

		/// <summary>
		/// Creates a closured method in the current scope's closure type using argument types.
		/// </summary>
		public MethodEntity CreateClosureMethod(Context ctx, Type[] args, Type returnType = null)
		{
		}

		/// <summary>
		/// Finds a local name and invoke a callback.
		/// </summary>
		private bool find(string name, Action<LocalName, int> action = null)
		{
			var idx = 0;
			var frame = this;
			while (frame != null)
			{
				LocalName loc;
				if (frame.Names.TryGetValue(name, out loc))
				{
					if (action != null)
						action(loc, idx);
					return true;
				}

				if(frame.IsClosureSignificant)
					idx++;

				frame = frame.OuterScope;
			}

			return false;
		}

		#endregion
	}
}
